# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12
exclude: "node_modules|.venv|venv|.mypy_cache|.pytest_cache|__pycache__"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--ignore=E501, E203, W503"]

  - repo: https://github.com/PyCQA/isort
    rev: 8.0.0
    hooks:
      - id: isort
