[project]
name = "kairo-p402"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery[redis]>=5.6.2",
    "daphne>=4.2.1",
    "django>=6.0.2",
    "django-htmx>=1.27.0",
    "django-widget-tweaks>=1.5.1",
    "pre-commit>=4.5.1",
    "psycopg2-binary>=2.9.11",
    "pytest-django>=4.12.0",
    "pytest-playwright>=0.7.2",
    "python-decouple>=3.8",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"

python_files = "test.py tests.py test_*.py tests_*.py"

addopts = "-s"
